name: Java CI with Maven
on:
   push:
      branches:
      - master
   pull_request:
      branches:
      - master
jobs:
   build:
      runs-on: ${{matrix.os}}
      strategy:
         matrix:
            os:
            - ubuntu-latest
            - windows-latest
            java:
            - 11
            - 13
      name: Java ${{matrix.java}} build on ${{matrix.os}}
      steps:
      -  name: Set git to not mess with line endings
         run: |
            git config --global core.autocrlf false
      -  uses: actions/checkout@v2
         with:
            submodules: true
      -  name: Set up JDK ${{matrix.java}}
         uses: actions/setup-java@v1
         with:
            java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
         path: ~/.m2
         key: m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: m2
      -  name: Build with Maven
         run: mvn -B verify package --file pom.xml
      - run: mkdir staging && cp ktlsh/target/*.jar ktlsh-jmh/benchmarks.jar staging
      - uses: actions/upload-artifact@v1
        with:
            name: Package
            path: staging
# This operation gets cancelled
# name: Run benchmarks
# run: java -jar benchmarks.jar
# working-directory: ktlsh-jmh/target

